Refactoring
SoPra-Team-10/Client pull request #48
Opened 2019-06-17 13:59 UTC by Mvsvh

- Alle Fehlermeldungen wurden aufgelöst. 
- Einheitlicher Code-Style
- Reihenfolge und Syntax nach den Vue Core Team Recommendations
- Überarbeitung mancher Funktionen
- Auslagerung von universellem Code

2019-06-24 09:53 UTC, TarikEnderes requested changes
Kannst du die Einrückung wieder auf 4 Leerzeichen ändern?

2019-06-25 23:05 UTC, Mvsvh commented
Hab ich grad nicht die Nerven für. Der Standard ist 2 Spaces und ich müsste ca. ne halbe Stunde recherchieren um das rauszufinden. Ist es ok, wenn wir die 2 Spaces jetzt lassen? Kann die Tage auch nochmal recherchieren. Aber ich würde im Moment eher schauen, dass alles andere ordentlich wird.

2019-06-26 12:07 UTC, TarikEnderes commented
Es ist nie ordentlich mit zwei Space Einrückung, aber gut, von mir aus, solange alles läuft.

2019-06-26 12:10 UTC, TarikEnderes approved these changes

2019-06-27 09:33 UTC, TarikEnderes requested changes
Errors und Warnings nicht in-game in den Spielhinweisen anzeigen.

Bild auf dem Pause-Fortsetzen Button sind vertauscht.

Chance für erfolgreichen Wurf wird zweimal angezeigt.

Vielleicht noch kleine Animation einbauen, die die Wappen als klickbar erkennbar macht. (Z.B. weißer rand oder verdunkeln wenn man mit der Maus darüber fährt.)

2019-06-27 10:47 UTC, Mvsvh commented
> Errors und Warnings nicht in-game in den Spielhinweisen anzeigen.
> 
> Bild auf dem Pause-Fortsetzen Button sind vertauscht.
> 
> Chance für erfolgreichen Wurf wird zweimal angezeigt.
> 
> Vielleicht noch kleine Animation einbauen, die die Wappen als klickbar erkennbar macht. (Z.B. weißer rand oder verdunkeln wenn man mit der Maus darüber fährt.)

Hab die Sachen geändert/implementiert.

2019-06-27 17:48 UTC, merged